name: jobseeker
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  
  # http: ^0.12.2

  # Firebase
  firebase_core: ^0.7.0

  # Authentication
  firebase_auth: ^0.20.1
  google_sign_in: ^4.5.1
  flutter_signin_button: ^1.1.0

  # Firestore
  cloud_firestore: ^0.16.0 
  
  # Bloc
  flutter_bloc: ^6.1.3
  # flutter_form_bloc: ^0.19.0
  
  # state management
  provider: ^4.3.2+2

  # JSON
  json_annotation: ^3.1.1

  uuid: ^2.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # JSON
  build_runner: ^1.11.0
  json_serializable: ^3.5.1 

flutter:
  uses-material-design: true
